### PR TITLE
improved xslt caching, slf4j logging

### LINKED ISSUE #99: Hardcoded logfile path in log4j2.xml
src/main/resources/log4j2.xml refers to /vol1/logs/corpus-frontend.log, which may not be present.

### PR DESCRIPTION
**Pull request by eduarddrenth**
fixes #99 

configuring logging is now installation/server responsibility

### CODE REVIEW

**Comment by jan-niestadt** [comment]
Thanks! Does this include a useful default logging configuration? In other words, if the application is installed, but nothing is done to configure logging, will errors still be logged somewhere (and if so, where)?

I think useful default settings are very important for making it easy to get started with projects. Later on, someone running the application can figure out how to configure logging to his liking, but you ideally shouldn't have to do anything up front to get something working.

**Comment by eduarddrenth** [comment]
I'll check....

**Comment by eduarddrenth** [comment]
I introduced a runtime dep on slf4j-jdk14, meaning jul is used, which is the default for tomcat/glassfish. Without configuration jul will log to console at level INFO.  
Without this runtime dep you will see no logging. Made ths dep optional to help prevent multiple logging implementation problems.

**Comment by jan-niestadt** [comment]
Sounds great, thanks!

**Comment by eduarddrenth** [comment]
Don't forget this one please, I had a bit of a nasty merge already

**Pull request merged**
