### PR TITLE
fixes #33, #30 and #34, properties as dropdown

### LINKED ISSUE #33: loosing servlet context when clicking on index link

### PR DESCRIPTION
**Pull request by eduarddrenth**
url encoding utf-8, no more need for servlet container config
    default tomcat servlet in webapp
    relative url's working

### CODE REVIEW

**Comment by KCMertens** [comment]
Just a remark: searching for a sequence of values in props that are now selectboxes is longer possible (though admittedly it's always been a bit of a hidden feature). 

The normal word/lemma props will probably never be a select input, so it won't be an issue there, but searching for sequences in other props, such as `pos = adj nou` might be something that some users need to do?

**Comment by eduarddrenth** [comment]
I realized, but users can still use the cql tab and properties for which this "hidden feature" is important can be plain text fields. Perhaps ``<select multiple....``? Have been testing that, had some side effects though, maybe give it another try, but I think it is quite ok like this.

**Comment by KCMertens** [comment]
`<select multiple/>` will make bootstrap-select return an array from val(), js code in singlepage-form and singlepage-bls expects it to be string, so it makes sense that will result in issues. Could be solved by making the singlepage-form setValue handle arrays, and joining the values with regex `|` in singlepage-bls if there's more than one.

**Comment by eduarddrenth** [comment]
ok, thanks for the info, I suggest we leave that a todo. What is there now is a good improvement and there is always the cql tab.

**Comment by jan-niestadt** [comment]
Is it necessary to add the `listvalues` property to corpus-frontend.properties (the admin prop file)? Wouldn't putting a `uiType` on the annotation be enough to trigger the select behaviour?

**Comment by eduarddrenth** [comment]
I've been trying to extend PropertyDesc with a uiType, but did not manage to get that filled, mainly because PropertyDesc is constructed from lucene index info, the uiType field has to be filled somewhere later from metainfo, several complications with that.
And than the blacklab output has to be adapted and picked up in the frontend.
The impact of this is pretty high (for me it is :-))

**Comment by jan-niestadt** [comment]
I'll have a look at it soon.

**Comment by eduarddrenth** [comment]
And the generation of the metainfo has to be adapted as well. But a uiType solution is more flexible and tied to an index and not to the whole app. Though for a simple one instance setup (the majority?) the property solution is clean and simple.

**Comment by KCMertens** [comment]
Does this depend on https://github.com/INL/BlackLab/pull/52 or the proposed changes in https://github.com/INL/corpus-frontend/issues/39, or can this be safely merged already? 

@jan-niestadt has some more work he wants to do on PropertyDesc in addition to adding a uiType, so my question is whether you'd rather wait for him to finish that and update this pr prior to merging, or not. (assuming this is not waiting for any work in the other mentioned issues)
My preference would be to merge this now, then do another update later when uiType has been added.

**Comment by eduarddrenth** [comment]
no, does not depend on that

**Comment by eduarddrenth** [comment]
The uiType in PropertyDesc can override a listvalues property

**Pull request merged**
