### PR TITLE
configurable which props to show in columns

### PR DESCRIPTION
**Pull request by eduarddrenth**
helps with #62 

screenshot from 2018-04-06 07-22-23

### CODE REVIEW

**Comment by eduarddrenth** [comment]
Does this have any attention? Low risk PR I think, useful to others as well.

**Comment by KCMertens** [comment]
Was just looking at it actually.
I think the JS needs a little more tact though, search.xml can't be configured for user corpora, so no info would be shown at all if they don't have pos or word.

Maybe we could do as Jan suggests:
> never show more than 3 (?) properties in the table (default value, perhaps overridable in corpus-frontend.properties)
prefer showing lemma and pos if they exist (again, default value that could perhaps be overridden)

So show the first 3 props from the format, giving preference to pos/word if they are present, but if it's configured in search.xml for then use that list.

**Comment by KCMertens** [comment]
If that seems like a sensible solution, I can add it when merging?

**Comment by eduarddrenth** [comment]
pos and lemma are shown by default, also for user corpora...

**Comment by eduarddrenth** [comment]
No, I realy want to show specific columns. I may solve that in css/js though, but this PR is simple , more clean and without risc.

**Comment by KCMertens** [comment]
>pos and lemma are shown by default, also for user corpora...

I'm only referring to the default case where nothing is configured at all. If you configure through `search.xml` then it should of course just do as you expect. 

The issue I have is when a corpus that has no configuration (such as a user corpus, which _cannot_ be configured) does not contain lemma/pos, no props are shown at all. In this implementation no properties would be shown at all. 

What I propose is when this happens, to use lemma/pos _if they exist in the corpus_, and if they don't to just use the first 2 or 3 properties that are defined.

**Comment by KCMertens** [comment]
That'd be great! I think it should be pretty easy by checking the the PropertyFields from the CorpusConfig while parsing the WebsiteConfig.

**Comment by eduarddrenth** [comment]
leave it, I'll adapt to make the defaults work as you suggest

**Comment by eduarddrenth** [comment]
tested, pushed, one TODO in websiteconfig, maybe you can take a look

**Comment by KCMertens** [comment]
Looks good, I'll give it a whirl and fix up that todo when I'm back at the office.

**Pull request merged**
