### PR TITLE
Add /config page, returns part of the .properties file as json

### PR DESCRIPTION
**Pull request by KCMertens**
Required for integration with Galahad

### CODE REVIEW

**Comment by tcbrouwer** [comment]
I don't know what the expected behaviour is, but currently the config response will be send not only at corpus-frontend/config but also at corpus-frontend/any_string_could_be_index/config

This might be just fine, but in my setup I was using the config object as a confirmation that the url was a valid corpus-frontend endpoint. I can not use corpus-frontend/any_string/ as main endpoint, so validating like this doesn't work. Using the config like this is a bit of a hack, but just food for thougth.

**Comment by KCMertens** [comment]
Yes that's a bit of an interesting "feature", all pages can be served in the context of a corpus. 
corpus-frontend/<any_corpus>/corpora is also an interesting one, you'll get the corpus listing but styled as if you're inside a corpus already (if the corpus has styling info). 

I'd consider this to be undocumented behavior that just happens to work, but might not always. 
As long as it's not causing any problems I don't see a reason to go out of our way to remove it now.

**Comment by KCMertens** [comment]
You could always use the /search page to test for a corpus, that one requires a corpus to be set and so returns 404 when the corpus isn't found.

**Comment by tcbrouwer** [comment]
Ok sounds good

**Review by tcbrouwer — APPROVED** [review]
LGTM & thanks

**Pull request merged**
