### PR TITLE
Made properties in hits table dynamic

### PR DESCRIPTION
**Pull request by dafnevk**
Instead of 'Lemma' and 'Part of speech' the hits table now shows the properties that are available for these hits.

### CODE REVIEW

**Comment by KCMertens** [comment]
Thanks! That's one of those things that's been on the TODO list for too long already. 

I have one question, the "hit text" (`word`) property is now shown twice. 
Instead we could display the `mainProperty` as the "hit text" (or properties - one per complexField, though there's normally only one of those). Then those highlighted props could be skipped in the extra columns to save some space.

Also, could change this PR to the dev branch?

**Comment by eduarddrenth** [comment]
Nice, but perhaps some configuration is needed, if there are many properties the table may have too many columns to fit.

**Comment by eduarddrenth** [comment]
And the properties are already shown if you click on a hit

**Comment by KCMertens** [comment]
> And the properties are already shown if you click on a hit

That doesn't allow sorting though.

**Comment by eduarddrenth** [comment]
true, sorting on props is a nice feature, I assume blacklab is called to sort?

**Comment by KCMertens** [comment]
Correct, the frontend really doesn't do much, it mostly just requests a new set of results whenever something changes.

**Comment by dafnevk** [comment]
I changed it so that the main property it not shown in the extra columns. It might not work as expected if there are multiple main properties.

**Comment by KCMertens** [comment]
My mistake - I'll fix those conflicts locally

**Pull request merged**
